from . import change_price_kb
from . import cities_kb
from . import distance_kb
from . import go_back_kb
from . import history_kb
from . import hotels_kb
from . import main_menu_kb
from . import num_kb
from . import yes_no_kd
